---
- name: .NET CORE APPLICATION IIS SERVER DEPLOYMENT
  hosts: "{{ lookup('env','IIS_SERVER') }}"
  gather_facts: no
  tasks:
    
    - name: Creating website folder on IIS
      ansible.windows.win_file:
        path: "{{ lookup('env','WEB_PATH') }}"
        state: directory

    - name: Create a new application pool in 'Started' state
      community.windows.win_iis_webapppool:
        name: "{{ lookup('env','POOL_NAME') }}"
        state: started

    - name: Crate IIS site and stop for update
      community.windows.win_iis_website:
        name: "{{ lookup('env','WEB_NAME') }}"
        state: stopped
        port: "{{ lookup('env','WEB_PORT') }}"
        ip: "{{ lookup('env','WEB_IP') }}"
        hostname: "{{ lookup('env','WEB_HOSTNAME') }}"
        application_pool: "{{ lookup('env','POOL_NAME') }}"
        physical_path: "{{ lookup('env','WEB_PATH') }}"
    
    - name: Copy built-app folder contents recursively to IIS WEB folder
      ansible.windows.win_copy:
        src: "{{ lookup('env','BUILD_ARTIFACT_PATH') }}"
        dest: "{{ lookup('env','WEB_PATH') }}"

    - name: Start IIS site
      community.windows.win_iis_website:
        name: "{{ lookup('env','WEB_NAME') }}"
        state: started
      register: website

    - name: IIS Pool Info
      debug:
        var: website


...
